{{ $key := default (randAlphaNum 10) .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forwarder.fullname" . }}
type: Opaque
data:
  APP_ALERTMANAGER_SECRET: {{ default (randAlphaNum 32) .Values.app.alertmanager.secret | b64enc }}
  MATRIX_HOMESERVER_URL: {{ .Values.matrix.homeserver_url | b64enc }}
  MATRIX_ROOMS: {{ .Values.matrix.rooms | b64enc }}
  MATRIX_TOKEN:  {{ .Values.matrix.token | b64enc }}
  MATRIX_USER: {{ .Values.matrix.user | b64enc }}
  MENTION_ROOM: {{ .Values.matrix.mention_room | b64enc }}
